# Generated by Django 4.2 on 2023-05-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_currencyconversion_start_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyconversion',
            name='start_currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('GBP', 'GBP'), ('USD', 'USD')], max_length=3),
        ),
        migrations.AlterField(
            model_name='currencyconversion',
            name='target_currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('GBP', 'GBP'), ('USD', 'USD')], max_length=3),
        ),
    ]
