# Generated by Django 4.2 on 2023-05-02 03:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0002_alter_notifications_time_of_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='time_of_notification',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 2, 3, 23, 26, 991177, tzinfo=datetime.timezone.utc)),
        ),
    ]
