# Generated by Django 4.2 on 2023-05-02 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0005_alter_notifications_time_of_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='time_of_notification',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 2, 18, 6, 8, 831677, tzinfo=datetime.timezone.utc)),
        ),
    ]
