# Generated by Django 4.2 on 2023-05-02 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0007_alter_notifications_time_of_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='time_of_notification',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 2, 22, 16, 0, 612176, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='type_of_transaction',
            field=models.CharField(choices=[('requested', 'has requested a payment of'), ('rejected', 'has rejected the requested payment of'), ('paid', 'has paid the requested payment of'), ('sent', 'You sent a payment of'), ('request', 'You requested a payment of')], max_length=50),
        ),
    ]
