# Generated by Django 4.2 on 2023-05-02 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0009_alter_notifications_time_of_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='time_of_notification',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 2, 23, 52, 50, 956897, tzinfo=datetime.timezone.utc)),
        ),
    ]
